[package]
name = "point24"
version = "0.1.0"
authors = ["Junfeng Liu <china.liujunfeng@gmail.com>"]
edition = "2018"

[dependencies.num-rational]
version = "0.2"
default-features = false
features = ["std"]

[dependencies.num-traits]
version = "0.2.4"
default-features = false
